### ISSUE TITLE
Add Tailwind v3 colors, shadows and fonts sizes

### ISSUE THREAD

**Issue by the94air** [the94air/twcopy#49]
TailwindCopy is a tiny website that allows you to copy tailwind colors, shadows, font sizes easily https://twcopy.js.org. It's a static site build with Nuxtjs. The main use of this tool is when you're working on something outside of Tailwind zone. I personally use it a lot while designing or sketching.
The required feature is to add another section that holds the tailwind v3 colors, shadows, font sizes. Changes will be expected on the side menu by adding another button with "v3" and showing the correct data on the main section on the right. The data should be taken from the current tailwind documentation. Let me know if you need any help!
I will add a link to the contributors page on README once the PR is accepted and merged! Thank you!

**Comment by alexjharrison** [comment]
I'd like to be assigned this issue. Thanks!

**Comment by the94air** [comment]
@alexjharrison Feel free to ask for help if needed! 👍
